### ISSUE TITLE
TestForAPIShowingAllFeatures  issue

### ISSUE THREAD

**Issue by supertrizero** [Cammin/LDtkUnity#13]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/5143332/115108837-1b37e400-9fa5-11eb-9d18-8747441cfe72.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/5143332/115108842-2ab72d00-9fa5-11eb-81ef-e39a8fbe8eec.png">

not the same , will fix it  in 1.3.9?

**Comment by Cammin** [comment]
There are still some differences in appearance for some aspects. It's something I'm trying to work towards soon. It may not come next update, but definitely a big priority of mine 😃 

The main differences here are with the entity's size, and also with the int grid values colours.
In the Int Grid section of the Project, there is a toggle to turn off the rendering or the int grid value colours.

However, LDtk allows rendering the int grid values per layer whereas, in unity, it's only an option for all or none. So I'm going to experiment with only allowing individual layers as well.

Thank you for letting me know about this 👍

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [int grid values visible for specific layers instead of all](https://trello.com/c/QWNqCZvH/246-int-grid-values-visible-for-specific-layers-instead-of-all)

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review the TestAllAPI and ensure everything looks exactly as it does in LDtk](https://trello.com/c/JBKcjVP8/247-review-the-testallapi-and-ensure-everything-looks-exactly-as-it-does-in-ldtk)

**Comment by Cammin** [comment]
I pushed a new major update that potentially fixes how its example looks. Check out all of its details here: https://github.com/Cammin/LDtkUnity/blob/master/Assets/LDtkUnity/CHANGELOG.md

The entities with a hollow rectangle are still opaque, but it's something I'm currently working on. I'll update you when that's added 🙂

**Comment by Cammin** [comment]
I'm leaving this issue as resolved, but feel free to reopen if necessary 🙂
