### ISSUE TITLE
Conflict with Odin Inspector when drawing arrays

### ISSUE THREAD

**Issue by Sookhaal** [Cammin/LDtkUnity#14]
Whenever Odin is active and an array with the LDtkField attribute is drawn on the inspector, a weird graphic bug happens.
The ldtk icon `d_SimpleIcon.png` gets drawn everywhere and every tooltips get messed up.

With Odin active and no arrays opened, everything is working as expected:
![odin and arrays not opened](https://user-images.githubusercontent.com/6463171/118128665-7ec5fd80-b3fb-11eb-9977-bf2f8527035d.jpg)

But as soon as you open an array:
![odin and array opened](https://user-images.githubusercontent.com/6463171/118128780-a74df780-b3fb-11eb-8a2e-33ec512b2dcc.jpg)

And that icon is drawn every where in Unity:
![Screenshot 2021-05-13 144344](https://user-images.githubusercontent.com/6463171/118128851-bdf44e80-b3fb-11eb-8678-c0f155b33794.jpg)

Also the tooltip gets drawn at the bottom of the inspector (it was working well before opening up the array):
![tooltip position](https://user-images.githubusercontent.com/6463171/118128947-d82e2c80-b3fb-11eb-8dd7-47f8e89a5df8.jpg)

I did a temporary fix to quickly solve the issue on my side, but I'd rather have a proper fix if possible:
```csharp
// Inside LDtkUnity/Editor/LDtkFieldAttributeDrawer.cs
public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
{
#if ODIN_INSPECTOR
    if (property.name != "data") {
        label.image = LDtkIconLoader.LoadSimpleIcon();
        label.tooltip = "'This field is sed by LDtk";
     }
#else
      label.image = LDtkIconLoader.LoadSimpleIcon();
      label.tooltip = "'This field is sed by LDtk";
#endif
    EditorGUI.PropertyField(position, property, label);
}
```

**Comment by Cammin** [comment]
Very interesting bug. I'll address it as soon as I can and push a hotfix.

I believe that a proper fix would be to construct a new GUIContent instead of using the existing one passed in the function. What's likely happening is this GUIContent is passed around for the rest of the drawers in Unity/Odin. My mistake 😅 

Also, I noticed that the tooltip has a couple typos in it so that will be fixed too.

Thanks for reaching out to me on this! This is well documented. 🙂

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the property drawer LDtkAttribute for Odin](https://trello.com/c/mRPChMhD/276-fix-the-property-drawer-ldtkattribute-for-odin)

**Comment by Cammin** [comment]
I tested with Odin and can verify it's fixed. It's in the package update 1.3.9. 👍 
Here was my solution: 9d2d3d8

**Comment by Sookhaal** [comment]
Awesome, thanks for the fix! Great job with that package :)
