### ISSUE TITLE
composite collider 

### ISSUE THREAD

**Issue by Parachutexd** [Cammin/LDtkUnity#18]
Hey Cammin, GREAT WORK! 
Your 2.0 version just brings LDtktoUnity into another level!
Just one quick question, can I generate Composite Collider 2D by default instead of only Tilemap Collider 2D?

**Comment by Cammin** [comment]
Yes, this is something I have planned to add soon, actually. It's definitely useful for preventing lag in the editor, particularly when trying to move a level in the GridVania sample.

For the current moment, you can add a composite collider 2d to the tilemap GameObjects into the scene, but I understand it's some manual work. 😅

I'll let you know when this feature gets added.
Thanks for the kind words 🙂

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add option to add a compositecollider2d](https://trello.com/c/kTjeYFDM/289-add-option-to-add-a-compositecollider2d)

**Comment by Parachutexd** [comment]
Great! Thank you very much!

**Comment by Cammin** [comment]
I just pushed an update that adds a toggle for a CompositeCollider2D. Let me know what you think. 
![image](https://user-images.githubusercontent.com/55564581/120967378-3a88fd00-c71c-11eb-95b7-71dc06af3280.png)

It's in version 2.0.4: https://github.com/Cammin/LDtkUnity/blob/master/Assets/LDtkUnity/CHANGELOG.md

Closing this issue. Feel free to reopen if necessary. 🙂

**Comment by Parachutexd** [comment]
Awesome! It works perfectly for me. Thanks for your effort!
