### ISSUE TITLE
LDtkUnity.Example already exists 

### ISSUE THREAD

**Issue by troudki** [Cammin/LDtkUnity#2]
Hello Cammin, 
Thanks you and good luck to continue this package on Unity, it will be well received by the community. When we install the package by UPM (modification of the manifest), we get the runtime + Samples. Impossible to get the Samples via package manager/Samples/import, otherwise we have the following message in theconsole _Assembly console with name 'LDtkUnity.Example' already exists (Packages/com.cammin.ldtkunity/Samples/Example/LDtkUnity.Example.asmdef)_
![Capture](https://user-images.githubusercontent.com/938271/98942253-09ca4780-24ee-11eb-81d7-a00bfb5dfc39.PNG)

**Comment by Cammin** [comment]
Ah yes, that was an oversight on my part; will fix that, and thanks for pointing it out :)
