### ISSUE TITLE
LDtk added support for aseprite but LDtk to Unity can't handle them

### ISSUE THREAD

**Issue by stickynoteme** [Cammin/LDtkUnity#21]
LDtk added support for using aseprite files in it's last update, but any time I use one LDtk to Unity fails to import the project with a null error.

**Comment by Cammin** [comment]
I have not actually experimented with this yet, but I appreciate bringing this to light.
It's a task I already have on the Trello, so I'll bump this up to a high priority.

As for importing aseprite files themselves, I may have to write a standalone aseprite asset importer, or use an aseprite Unity importer that already exists.

But I'll let you know when this feature is added 🙂

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [figure out what might happen if we try using LDtk's aseprite integration and if it's usable in some capacity](https://trello.com/c/dVVBzMQt/262-figure-out-what-might-happen-if-we-try-using-ldtks-aseprite-integration-and-if-its-usable-in-some-capacity)

**Comment by stickynoteme** [comment]
The Aseprite to Unity importer is pretty good. I use it a lot for animations. 

Link to the one I use in case you want it:
https://github.com/martinhodler/unity-aseprite-importer

**Comment by Cammin** [comment]
I pushed a new [update (2.0.5)](https://github.com/Cammin/LDtkUnity/blob/master/Assets/LDtkUnity/CHANGELOG.md) which adds a safeguard when trying to load Aseprite files instead of where a texture file would normally be loaded so that the LDtk project is still imported safely.

However, I'm going to be leaving this feature unsupported at least for now until I get around to prioritizing this addition, and when I can find the cleanest solution possible. I want to avoid depending on external packages as much as possible unless I must.  
![image](https://user-images.githubusercontent.com/55564581/121822937-cf2cb700-cc56-11eb-8428-75e178d44d7b.png)

So for now, exporting Aseprite files to PNGs is the way to go. 
Hopefully, it's not a huge problem 😅

**Comment by Cammin** [comment]
The unity aseprite importer by martinhodler uses a license (GPL-3.0) that is quite restrictive for what I'd want to do with it.
So I was instead looking around to find an aseprite importer, and found a decent one with an MIT license, and it actually looks really clean, and is also compatible for aseprite 1.3 (I think): https://github.com/negi0109/unity-aseprite-importer

I'm planning on making a custom implementation based off the code from that repo to properly load aseprite files, just like how LDtk loads their aseprite files.

It's certainly going to happen, but not next update, as I'm currently working on adding new features to match with LDtk's 1.0 update 👍

**Comment by dcheglakov** [comment]
@Cammin thank you. We're looking forward to this feature. We hope it won't take long.

**Comment by dooderino** [comment]
+1, love your tool and this is the feature I'd love to have most.

**Comment by Cammin** [comment]
Yep, I keep on thinking about adding this soon. :)
Currently just focusing on more integral features like performance, but aseprite file support should be coming soon enough 🙂

**Comment by Cammin** [comment]
An update on this: Unity has its own official Aseprite importer. It is however in a prerelease state. But, I think this will be the right way to go forward with supporting aseprite files with the importer in the future. It's still a low priority relative to some other things I'm working on, but unity's own aseprite package should be gaining some updates in the meantime to become stable for my own use. Once it's out of a prerelease state, that will be a good time for me to try using that importer to generate textures from 🙂 

I've also heard that the aseprite support in ldtk appears to have minor issues based on some mentions I've seen previously. Exporting to a png is still the tried and true process, but there are certainly some workflow benefits from directly loading aseprite files 🙂

**Comment by Cammin** [comment]
The newest update (4.1.0) adds Aseprite support! Just install Unity's Aseprite importer, and LDtk will be able to load them 🙂 (The Aseprite importer requires Unity 2021.3.15)

Also added some docs about it [here](https://cammin.github.io/LDtkToUnity/documentation/Installation/topic_StartupGuide.html#4-texture-change)
