### ISSUE TITLE
Is there a way to load the LDtk File as a gameobject?

### ISSUE THREAD

**Issue by dataEcto** [Cammin/LDtkUnity#3]
A bit of a weird question here. I was wondering if it was at all possible for the LDtk File to be loaded in as a game object using LDtkUnity, rather than only have it build during Play Mode.

**Comment by Cammin** [comment]
I am actually currently working on a feature to generate levels into the scene outside of playmode. It should be coming in the next update. :)

**Comment by AndyGFX** [comment]
Assets\Tests\Editor\FieldDeserializeTest.cs(5,17): error CS0234: The type or namespace name 'Test_file_for_API_showing_all_features' does not exist in the namespace 'LDtkUnity' (are you missing an assembly reference?)

**Comment by Cammin** [comment]
@dataEcto The newest update adds the ability to create levels in edit mode, so This issue is resolved. Check out the changelog if you're interested in what was added :)

@AndyGFX Thank you for pointing out the issue. I'll get that fixed in a hotfix.
