### ISSUE TITLE
Individual level files not working

### ISSUE THREAD

**Issue by marcgrabow** [Cammin/LDtkUnity#36]
First of all, thank you very much for making this plugin. I can see there is a lot of work that went into this! Thanks for that.

I was wondering if the "individual level file" feature should still work, because I can't get it to work in my environment. 

* When using the project file, everything gets imported correctly and works as expected
* When changing the LDtk setting to "Save levels to separate files" and checking those individual ldtkl files in the Unity project view, those do not have the expected game objects under them, just look like this:

![image](https://user-images.githubusercontent.com/2490992/152181362-e7979ab9-e7a3-4717-8241-987d7b639c83.png)

I am using
* Unity 2021.2.8
* LDtkToUnity 2.1.8
* LDtk 0.9.3

Am I doing something wrong?

**Comment by Cammin** [comment]
Ah yes, that's the old editor inspector for level files.
The new separate level files are available by using the newest version of the package: 2.1.8 -> 2.2.0
You can update the package from the package manager window:
https://cammin.github.io/LDtkToUnity/documentation/Installation/topic_Update.html
Thanks for trying out the importer! 🙂

**Comment by marcgrabow** [comment]
Ha, I didn't even check if there is an update as I only recently got it and didn't realise you are that active on this, that's awesome.

Update obviously solved it, thanks a lot!
