### ISSUE TITLE
[Feature Request] Support External Enums which are imported.

### ISSUE THREAD

**Issue by JustusPan** [Cammin/LDtkUnity#42]
Current version: LDtkToUnity v3.1.3

The imported enums has different data path from the built-in enums of LDtk.
Could we also support external Enums?
external Enums allow us maintian the full Enums list in an external file and import/refresh from that file, which is more feasible for a serious project.

**Comment by Cammin** [comment]
Yep, it's something to be added. I'm keeping note of it :)

**Comment by Cammin** [comment]
After looking into this, LDtk references the external enum, but still loads it into the project json. So it's retroactively always been supported 😅
