### ISSUE TITLE
[Error] LDtk: Didn't load texture at path "" when setting up field slices

### ISSUE THREAD

**Issue by JustusPan** [Cammin/LDtkUnity#45]
![image](https://user-images.githubusercontent.com/10916383/207667742-b9fff35b-1ac8-4756-9d18-bcda24dea07f.png)
![image](https://user-images.githubusercontent.com/10916383/207667993-a7d7c23f-ba20-4363-acb1-4dc000f6eeca.png)

if I put an entity who has a field with type "tile" in the level. An error message will be reported as what issue title shown.

**Comment by Cammin** [comment]
I released a new major update that changes enough to require revisiting this issue. Let me know if this is still a problem. Otherwise, I will label this issue as resolved sometime after a week or so has passed.
