### ISSUE TITLE
Rectangle entity grid size mismatch

### ISSUE THREAD

**Issue by codetaylor** [Cammin/LDtkUnity#46]
Hello, thank you for this amazing tool! 

![image](https://user-images.githubusercontent.com/1240716/221008025-9c8a09a3-dd1c-474f-88e3-a0df9fb95f71.png)
I have two layers, one IntGrid with rules and one Entity layer.

The IntGrid layer has a grid size of 16 and the Entity layer is 8.

![image](https://user-images.githubusercontent.com/1240716/221008336-d08114b9-d50d-40fb-97fc-9f4b4dc11c5d.png)
Snapping a rectangle entity on the 8x8 Entity layer works as expected in LDtk.

![image](https://user-images.githubusercontent.com/1240716/221008534-99ce26d4-874e-4deb-8157-cc5f3192c641.png)
When importing into Unity, the rectangle entity is twice the size it should be.

![image](https://user-images.githubusercontent.com/1240716/221008896-8a41750e-2a19-4d9e-b374-bee0f41974f4.png)
If I change the grid size of the Entity 8x8 layer to 16 before saving...

![image](https://user-images.githubusercontent.com/1240716/221009048-0f1d5174-11c4-4504-9a27-664927cd4d0d.png)
... the imported size is correct.

![image](https://user-images.githubusercontent.com/1240716/221009392-56e8c1b4-a849-414a-8dda-c93c8e43255e.png)

**Comment by Cammin** [comment]
Hi, I will look into this so the expected size remains. Thank you :)
For now, you can make the entity's grid size match the remaining standard of your project.

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rectangle entity grid size mismatch](https://trello.com/c/xiaI0zCk/904-rectangle-entity-grid-size-mismatch)

**Comment by Cammin** [comment]
Looking at this right now, it appears to only be a visual bug; the entity gameobject scale works as expected when I checked in the Entities example, though the scene-drawn box was twice the size, much like your issue above.

I will make a fix so that the editor gizmo is the expected size. But just know that it shouldn't functionally affect any of your objects in an unexpected way :)

**Comment by Cammin** [comment]
The fix is done :)
I'll pack it in with the next minor update and post back here

**Comment by Cammin** [comment]
Hi, the update with this fix is out! (3.3.2)
I will close this now, but feel free to reopen it if nessesary.
