### ISSUE TITLE
LDtk: Loading artifacts didn't work for getting tileset sprite artifacts

### ISSUE THREAD

**Issue by jackthecoder17** [Cammin/LDtkUnity#50]
I have followed instructions to import into unity but generated tilesets keep showing this error.

**Comment by Cammin** [comment]
During initial setup, you may come across various errors and this is normal. They should be able to tell you what to do.

For the generated tileset files that have an error, select the file, then click the "print to console" button. The error will point you in the right direction to fix it.

 Try following this guide if it may help: 
https://cammin.github.io/LDtkToUnity/documentation/Installation/topic_StartupGuide.html
It's a new page I created for the 4.0.0 update 🙂

**Comment by Cammin** [comment]
Also the docs currently don't  currently indicate that the texture needs to be configured with rgba32 format, but I have some new docs in the works to explain that 🙂

If you have additional questions, I'm actively available in the discord server.

**Comment by Cammin** [comment]
Hi, I'll be closing this issue, But feel free to let me know if you still need help! The docs should have an updated startup guide that explains the RGBA32 error.
