### ISSUE TITLE
[Feature Request] HotReload support

### ISSUE THREAD

**Issue by Fire-Aalt** [Cammin/LDtkUnity#53]
I am using [HotReload](https://assetstore.unity.com/packages/tools/utilities/hot-reload-edit-code-without-compiling-254358) in my project and when it is turned on the import process of the LDtk project is not triggered every time i save it in LDtk. I get the notification that everything has been imported but the levels did not update and post processors did not trigger.

Because of the nature of HotReload asset, it only reimports when the code change affects the editor thus breaking the import process in Unity.

**Comment by Cammin** [comment]
I'll continue this in a discord thread 🙂

**Comment by Fire-Aalt** [comment]
Ctrl+R to refresh Assets is the only way to reload project with HotReload turned on. It is the HotReload responsibility to add ScriptedImporters support
